package com.model;

/**
 * TCheci generated by MyEclipse Persistence Tools
 */

public class TCheci implements java.io.Serializable//因为这是一个Java实体类，里面有一个Spring用来管理、维护JavaBean之间的关系，满足JavaBean的条件之一就是要实现序列化接口
{

	private Integer id;
	
	private String riqi;
	private String bianhao;
	private String shifadi;
	private String daodadi;
	
	private String facheshi;
	private Integer shengpiao;
	private Integer chengrenpiaojia;
	
	private Integer ertongpiaojia;
	private String del;
	
	
	public String getBianhao()
	{
		return bianhao;
	}
	public void setBianhao(String bianhao)
	{
		this.bianhao = bianhao;
	}
	
	public Integer getChengrenpiaojia()
	{
		return chengrenpiaojia;
	}
	public void setChengrenpiaojia(Integer chengrenpiaojia)
	{
		this.chengrenpiaojia = chengrenpiaojia;
	}
	public String getDaodadi()
	{
		return daodadi;
	}
	public void setDaodadi(String daodadi)
	{
		this.daodadi = daodadi;
	}
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public Integer getErtongpiaojia()
	{
		return ertongpiaojia;
	}
	public void setErtongpiaojia(Integer ertongpiaojia)
	{
		this.ertongpiaojia = ertongpiaojia;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getFacheshi()
	{
		return facheshi;
	}
	public void setFacheshi(String facheshi)
	{
		this.facheshi = facheshi;
	}
	public String getRiqi()
	{
		return riqi;
	}
	public void setRiqi(String riqi)
	{
		this.riqi = riqi;
	}
	public Integer getShengpiao()
	{
		return shengpiao;
	}
	public void setShengpiao(Integer shengpiao)
	{
		this.shengpiao = shengpiao;
	}
	public String getShifadi()
	{
		return shifadi;
	}
	public void setShifadi(String shifadi)
	{
		this.shifadi = shifadi;
	}
	

}