package com.model;

/**
 * TCheci generated by MyEclipse Persistence Tools
 */

public class TGonggao implements java.io.Serializable//因为这是一个Java实体类，里面有一个Spring用来管理、维护JavaBean之间的关系，满足JavaBean的条件之一就是要实现序列化接口
{

	private Integer id;
	
	private String gonggao;

	private String del;
	

	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}

	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getGonggao()
	{
		return gonggao;
	}
	public void setGonggao(String gonggao)
	{
		this.gonggao = gonggao;
	}

	

}