package com.model;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TXunwu implements java.io.Serializable
{

	private Integer id;
	private String neirong;
	private String xunwushi;
	private Integer userId;

	private String huifu;
	private String huifushi;
	
	
	public String getHuifu()
	{
		return huifu;
	}
	public void setHuifu(String huifu)
	{
		this.huifu = huifu;
	}
	public String getHuifushi()
	{
		return huifushi;
	}
	public void setHuifushi(String huifushi)
	{
		this.huifushi = huifushi;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getXunwushi()
	{
		return xunwushi;
	}
	public void setXunwushi(String xunwushi)
	{
		this.xunwushi = xunwushi;
	}
	public String getNeirong()
	{
		return neirong;
	}
	public void setNeirong(String neirong)
	{
		this.neirong = neirong;
	}
	public Integer getUserId()
	{
		return userId;
	}
	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}
	
}